<!DOCTYPE html>
<html>
<body>

<div align="center">
<h3>Prepared by Shaig E.Kazimov</h3>
    
<h1>Python exercises</h1>

<h3>Follow Me on - <a href="https://www.linkedin.com/in/shaig-kazimov/">LinkedIn</a>&nbsp;

</div>
</body>
</html>

# Variables

Create a variable with name "x" and a value of 10. Execute.

In [ ]:
x = 10

Tell the computer to show you the value of that variable.

In [2]:
x=10
print(x)

10


Can you think of a second way to obtain the same result?

In [3]:
x

10

On the same line, create four new variables: a,b,c, and d, that are equal to 10, 20, 30, and 40, respectively.

In [7]:
a, b, c, d = 10, 20, 30, 40
print

<function print(*args, sep=' ', end='\n', file=None, flush=False)>

Tell the computer to show you the value corresponding to the variable "b".

In [8]:
print(b)

20


Do the same for "d".

In [9]:
print(d)

40


_________________________________

# Numbers and Boolean Values

Create a variable equal to "True".

In [10]:
a=True
print(a)

True


Check its type.

In [11]:
x=True
print(type(x))

<class 'bool'>


Create a variable equal to 99.

In [ ]:
y=99


Check its type.

In [12]:
print(type)

<class 'type'>


Check the type of the value 0.99.

In [13]:
z=0.99
print(type(z))  

<class 'float'>


Turn 99 into a float.

In [15]:
y=99
x=float(y)
print(x)
print(type(x))

99.0
<class 'float'>


Turn 0.99 into an integer. What value did you get?

In [16]:
z=0.99
x=int(z)
print(x)
print(type(x))

0
<class 'int'>


_________________________________

# Strings

Assign the value of 100 to the variable "m".

In [23]:
m="100"
print(m + " days")

100 days


With the help of the variable "m", write one line of code where the output after executuion would be 100 days.

Hint: You could provide four answers to this question!

In [24]:
m="100"
print(f"{m} days")

100 days


In [25]:
m = "100"
print("{} days".format(m))


100 days


In [26]:
m = "100"
print("%s days" % m)


100 days


Produce an output equal to It's cool, isn't it?

In [31]:
print("Its cool, isn't it?")

Its cool, isn't it?


Fix the string below.

In [27]:
x="Don't be shy"
print(x)

Don't be shy


Produce an output equal to Click "OK".

In [29]:
print('Click "OK"')

Click "OK"


Include a plus sign in your line of code to produce 'Big Houses'.

In [32]:
print("Big" + "Houses")

BigHouses


Include a trailing comma in your line of code to produce Big Houses.

In [33]:
print("Big", "Houses")

Big Houses


__________________

# Arithmetic operators

Combine 15 and 23.

In [34]:
a=15
b=23
print(a+b)

38


Subtract 50 from 26.

In [35]:
x=50
y=26
print(x-y)

24


Divide 20 by 4.

In [36]:
a=20
b=4
print(a/b)

5.0


Divide 22 by 4.

In [37]:
x=22
y=4
print(x/y)

5.5


Obtain the remainder of the division of 22 by 4.

In [38]:
a=22
b=4
result=a%b
print(result)

2


Divide the float 22 by 4.

In [40]:
a=22.0
b=4
result=a/b
print(result)

5.5


Multiply 6 by 8.

In [41]:
a=6
b=8
result=a*b
print(result)   

48


Raise 15 to the power of 2.

In [42]:
a=15
b=15**2
print(b)

225


_____________________

# The double-equality sign

Demonstrate that 100 is not equal to 98.

In [43]:
a=100
b=98
print(a!=b)

True


__________________________

# Reassign Values

Assign the value of 14 to a variable p.

In [44]:
a=14
p=14
print(a==p) 

True


Calculate p + 10.

In [ ]:
def calculate_result(p):
    result = (p + 10)
    print(result)


24


Now, assign 30 to the variable p.

In [163]:
def calculate_result(p):
    result = (p + 10)


Calculate p + 10.

In [164]:
def calculate_result(p):
    result = (p + 10)
    print(result)
calculate_result(30)


40


Observe how the value of p is always the last one you have assigned.

In [ ]:
the previous p value is always overwritten

___________________

# Indexing Elements

Extract the letter 'B' from "Bingo!".

In [49]:
word="Bingo"
letter=word[0]
print(letter)

B


Extract the letter "u" from "Constitution".

In [50]:
word="Constitution"
letter=word[7]
print(letter)

u


________________

# Structure Your Code with Indentation

Use indentation properly to print the result of the function with an argument of 3.

In [52]:
def ten(x):
    x += 10
    return x
print(ten(3))

13


___________________

# Comparison Operators

Verify that 25 is smaller than 30.

In [54]:
a=25
b=30
result=a<b
print(result)

True


Verify that 5 multiplied by 3 is less than or equal to 5 to the power of 3.

In [56]:
a=5
b=3
result=5*3
result2=5*5*5
result3=result2>result
print(result3)


True


Verify that 100 is equal to 10 square.

In [58]:
print(100 == 10**2)


True


In [ ]:
a=10
b=10*10*10*10*10*10*10*10*10*10
result=a==b
print(result)

10000000000


Verify that 53 is not equal to 46.

In [59]:
a=53
b=46
result=a!=b
print(result)

True


___________________

# Logical and Identity Operators 

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Check whether the following code is True or False.

False or not True and not False

In [60]:
logic = False or not True and not False
print(logic)


False


True and not False and True or not False

In [61]:
logic= True and not False and True or not False 
print(logic)

True


True or False and False

In [62]:
logic= True or False and False 
print(logic)

True


False and True or False

In [63]:
logic= False and True or False
print(logic)

False


Using an identity operator, verify that 10 is not the same as 12.

In [64]:
a=10
b=27
print(a is not b)


True


Using an identity operator, verify that 50 is the same as 50.

In [65]:
a=50
b=50
print(a is b)

True


____________________

# Introduction to the IF statement

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Create a two-line code that prints "The condition has been satisfied" if 5 is greater than 2.

In [70]:
if 5>2:
    print("The condition has been satisfied")


The condition has been satisfied


Assign 10 to the variable x and 25 to the variable y. In the same cell, create 2 conditional statements. Let the first one print "Both conditions are correct" if x is greater then 3 and y is greater than 13. Let the second one print "At least one of the conditions is false" if x is less than or equal to 3 and y is less than or equal to 13. Change the values assigned to x and y and re-run the cell to verify your code still works.

In [71]:
x=10
y=25
if x>3 and y>13:
    print("Both conditions are correct")
    if x<=3 and y<=13:
        print("At least one of the conditions is false")

Both conditions are correct


____________________________

# Add an ELSE Statement

Let x represent the number of orders received during a certain day. Assign 102 to x. Create a program that prints "A busy day" if x is greater than 100, and "A calm day" otherwise. Change x to 97 to verify your code works properly.

In [74]:
x=97
if x>100:
    print("A busy day")
else :
    print("A calm day")

A calm day


_________________

# Else if, for Brief - ELIF

Assign 200 to x. Create the following piece of code: If x > 200, print out "Big"; If x > 100 and x <= 200, print out "Average"; and If x <= 100, print out "Small". Use the If, Elif, and Else keywords in your code.

In [76]:
x=200
if x>200:
    print("Big")
elif x>100 and x<=200:
    print("Average")
else:
    print("Small")


Average


Change the initial value of x to see how your output will vary.

In [82]:
x = 100
if x > 100:
    print("Big")
elif x > 50 and x <= 100:
    print("Average")
else:
    print("Small")

Average


Keep the first two conditions of the previous code. Add a new ELIF statement, so that, eventually, the program prints "Small" if x >= 0 and x <= 100, and "Negative" if x < 0. Let x carry the value of 50 and then of -50 to check if your code is correct.

In [83]:
x = 200  

if x > 200:
    print("Big")
elif x > 100 and x <= 200:
    print("Average")
elif x >= 0 and x <= 100:
    print("Small")
else:
    print("Negative")

Average


_____________________

# Creating a Function with a Parameter

Define a function that returns a value equal to its argument multiplied by 2.

In [84]:
def ikikati(x):
    return x * 2

Define a funciton that returns a float value equal to its argument divided by 2.

In [86]:
def yari(x):
    return x / 2


_________________

# Another Way to Define a Function

Define a function that states the value of the argument accompanied by the phrase "Raised to the power of 2:" and returns a value equal to its argument raised to the power of 2. This time, use a new variable, called "result", in the body of the Function. Call the function with some argument to verify it works properly.

Hint: Your knowledge about stating multiple elements on a line can be of great help in solving this exercise!

In [93]:
def powered(x):
    result = x ** 2
    print(x, "Raised to the power of 2:", result)
    return result

powered(5)

5 Raised to the power of 2: 25


25

_____________

# Using a Function in Another Function

Define a function that adds 5 to the parameter. Then, define another function that will multiply the newly obtained number by 3. Verify your code was correct by calling the second function with an argument of 5. Was your output equal to 30?

In [94]:

def besekle(x):
    return x + 5

def uclecarp(x):
    return besekle(x) * 3
result = uclecarp(5)
print(result)


30


____________________

# Combining Conditional Statements and Functions

Define a function, called compare_the_two(), with two arguments. If the first one is greater than the second one, let it print "Greater". If the second one is greater, it should print "Less". Let it print "Equal" if the two values are the same number.

In [98]:
def karsilastir(x, y):
    if x > y:
        print("x is greater than y")
    elif x < y:
        print("x is less than y")
    else:
        print("x is equal to y")
    x = 23
    y = 48
    karsilastir(x, y)   
    print(karsilastir(23, 48))

__________________

# Notable Built-In Functions in Python

Obtain the maximum number among the values 25, 65, 890, and 15.

In [101]:
numbers= [25,65,890,15]
enbuyuk=max(numbers)
print(enbuyuk)

890


Obtain the minimum number among the values 25, 65, 890, and 15.

In [102]:
numbers=[25,65,890,15]
enkucuk=min(numbers)
print(enkucuk)

15


Find the absolute value of -100

In [ ]:
deger= -100
mutlak_deger=abs(deger)
print(kesin_deger)

100


Round the value of 55.5. Did you obtain 56.0?

In [104]:
deger=55.5
yuvarlanan_deger=round(deger)
print(yuvarlanan_deger)

56


Round 35.56789 to the third digit.

In [108]:
deger=35.56789
yuvarlanan_deger=round(deger,1)
print(yuvarlanan_deger) 

35.6


Find the sum of all elements in the provided list, called "Numbers".

In [ ]:
Numbers = [1, 5, 64, 24.5]

In [109]:
sayılar=[1,5,64,24.5]
sum(sayılar)
print(sum(sayılar))

94.5


Use a built-in function to raise 10 to the power of 3.

In [111]:
sonuc=pow(10,3)
print(sonuc)

1000


How many characters are there in the word "Elephant"?

In [112]:
kelimemiz="Elephant"
uzunluk=len(kelimemiz)
print(uzunluk)

8


Create a function, called "distance_from_zero", that returns the absolute value of a provided single argument and prints a statement "Not Possible" if the argument provided is not a number. Call the funtion with the values of -10 and "cat" to verify it works correctly.

In [113]:
def distance_from_zero(x):
    if isinstance(x, (int, float)): 
        return abs(x)
    else:
        print("Not Possible")





In [114]:
print(distance_from_zero(-10)) 

10


In [115]:
print(distance_from_zero("cat")) 

Not Possible
None


____________________

# Lists

Create a list, called "Numbers". Let it contain the numbers 10, 25, 40, and 50.

In [116]:
Numbers= [10,25,40,50]
print(Numbers)

[10, 25, 40, 50]


Print the second element from the list.

In [117]:
Numbers=[10,25,40,50]
print(Numbers[1])

25


Print the 0th element.

In [118]:
Numbers=[10,25,40,50]
print(Numbers[0])

10


Print the third-to-last element using a minus sign in the brackets.

In [119]:
Numbers=[10,25,40,50]
print(Numbers[-3])

25


Substitute the number 10 with the number 15.

In [120]:
Numbers= [10,25,40,50]
Numbers[0]=15
print(Numbers)

[15, 25, 40, 50]


Delete the number 25 from the Numbers list.

In [121]:
Numbers = [15,25,40,50]
Numbers.remove(25)
print(Numbers)

[15, 40, 50]


______________

# Help Yourself with Methods

Append the number 100 to the Numbers list.

In [122]:
Numbers = [15, 40, 50]
Numbers.append(100)
print(Numbers)

[15, 40, 50, 100]


With the help of the "extend method", add the numbers 115 an 140 to the list.

In [125]:
Numbers= [15, 40, 50, 100]
Numbers.extend([115, 140])
print(Numbers)

[15, 40, 50, 100, 115, 140]


Print a statement, saying "The fourth element of the Numbers list is:" and then designate the value of the fourth element. Use a trailing comma.

In [126]:
Numbers=[15, 40, 50, 100, 115, 140]
print("The fourth element of the Numbers list is:", Numbers[3])


The fourth element of the Numbers list is: 100


How many elements are there in the Numbers list?

In [127]:
Numbers=[15, 40, 50, 100, 115, 140]
print(len(Numbers))

6


________________

# List Slicing

In [ ]:
Numbers = Numbers = [15, 40, 50, 100, 115, 140]

Using list slicing, obtain the numbers 100 and 115.

In [128]:
Numbers= [15,40,50,100,115,140] 
subset=Numbers[3:5]
print(subset)

[100, 115]


Using slicing, extract the first four elements from the list.

Using slicing, extract all the elements from the list from the 3rd position onwards.

In [130]:
Numbers=[15, 40, 50, 100, 115, 140]
subset=Numbers[2:]
print(subset)

[50, 100, 115, 140]


Using slicing, extract the last 4 elements from the list.

In [131]:
Numbers= [15,40,50,100,115,140]
subset=Numbers[-4:]
print(subset)

[50, 100, 115, 140]


Which is the position of the value 15?

In [132]:
Numbers=[15, 40, 50, 100, 115, 140]
position=Numbers.index(15)
print(position)

0


Create a list, called "Two_Numbers". Let its elements be the values 1 and 2. Then, create a new one, named "All_Numbers", that will containt both the "Numbers" and the "Two_Numbers" lists.

In [133]:
Numbers= [15,40,50,100,115,140]
Two_Numbers=[1,2]
All_Numbers=Numbers + Two_Numbers
print(All_Numbers)

[15, 40, 50, 100, 115, 140, 1, 2]


Sort all the numbers in the "Numbers" list from the largest to the smallest.

In [134]:
Numbers=[15, 40, 50, 100, 115, 140,1,2]
Numbers.sort(reverse=True)
print(Numbers)


[140, 115, 100, 50, 40, 15, 2, 1]


__________________

# Tuples

Create a tuple, called "Cars", with elements "BMW", "Dodge", and "Ford".

In [135]:
Cars=("BMW", "Dodge", "Ford")
print(Cars)


('BMW', 'Dodge', 'Ford')


Access the second element of this tuple.

In [136]:
Cars= ("BMW", "Dodge", "Ford")
print(Cars[1])

Dodge


Call a method that would allow you to extract the provided name and age separately. Then print the "name" and "age" values to see if you worked correctly.

In [ ]:
name, age = 'Peter,24'

In [137]:
kisi= ("Peter",25)
name,age=kisi 
print("Name:", name)
print("Age:", age)


Name: Peter
Age: 25


Create a function that takes as arguments the two values of a rectangle and then returns the Area and the Perimeter of the rectangle. Call the function with arguments 2 and 10 to verify it worked correctly.

In [138]:
def rectangle_properties(length, width):
    area = length * width
    perimeter = 2 * (length + width)
    return area, perimeter
result = rectangle_properties(2, 10)

print("Area:", result[0])
print("Perimeter:", result[1])


Area: 20
Perimeter: 24


________________________

# Dictionaries

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

This is the menu of a close-by restaurant:

In [ ]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'}

What is the second meal in the list?

In [139]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'}
print(Menu['meal_2'])

Fries


Add a new meal - "Soup".

In [140]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'}
Menu.update({'meal_5': 'Soup'})
print(Menu)

{'meal_1': 'Spaghetti', 'meal_2': 'Fries', 'meal_3': 'Hamburger', 'meal_4': 'Lasagna', 'meal_5': 'Soup'}


Replace the Hamburger with a Cheeseburger.

In [141]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna', 'meal_5': 'Soup'}
Menu.update({'meal_3': 'Cheeseburger'})
print(Menu)

{'meal_1': 'Spaghetti', 'meal_2': 'Fries', 'meal_3': 'Cheeseburger', 'meal_4': 'Lasagna', 'meal_5': 'Soup'}


Attach the Desserts list in the form of a sixth meal.

In [ ]:
Dessert = ['Pancakes', 'Ice-cream', 'Tiramisu']

In [142]:
Menu = {'meal_1':'Spaghetti', 
        'meal_2':'Fries', 
        'meal_3':'Cheeseburger', 
        'meal_4':'Lasagna', 
        'meal_5':'Soup'}

Desserts = ['Pancakes', 'Ice-cream', 'Tiramisu']
Menu['meal_6']=Desserts
print(Menu)

{'meal_1': 'Spaghetti', 'meal_2': 'Fries', 'meal_3': 'Cheeseburger', 'meal_4': 'Lasagna', 'meal_5': 'Soup', 'meal_6': ['Pancakes', 'Ice-cream', 'Tiramisu']}


Create a new dictionary that contains the first five meals as keys and assign the following five values as prices (in dollars): 10, 5, 8, 12, 5. Start by Price_list = {}.

In [143]:

Price_list = {}

Price_list['meal_1'] = 10
Price_list['meal_2'] = 5
Price_list['meal_3'] = 8
Price_list['meal_4'] = 12
Price_list['meal_5'] = 5

print(Price_list)


{'meal_1': 10, 'meal_2': 5, 'meal_3': 8, 'meal_4': 12, 'meal_5': 5}


Use the .get() method to check the price of the Spaghetti.

In [144]:
Price_list = {'meal_1': 10, 'meal_2': 5, 'meal_3': 8, 'meal_4': 12, 'meal_5': 5}

print("The price of Spaghetti is:", Price_list.get('meal_1'))


The price of Spaghetti is: 10


_____________________

# For Loops

Create a For loop that prints every digit on a new line.

In [ ]:
digits = [0,1,2,3,4,5,6,7,8,9]

In [146]:
digits = [0,1,2,3,4,5,6,7,8,9]
for d in digits:
    print(d)
    print(d**2)

0
0
1
1
2
4
3
9
4
16
5
25
6
36
7
49
8
64
9
81


Adjust the code, so the digits are all printed on the same line.

In [148]:
digits=[0,1,2,3,4,5,6,7,8,9]
for d in digits:
    print(d, end=' ')

0 1 2 3 4 5 6 7 8 9 

________________

# While Loops and Incrementing

Suggested Answers follow (usually there are multiple ways to solve a problem in Python).

Create a while loop that will print all odd numbers from 0 to 30 on the same row.

Hint: There are two ways in which you can create the odd values!

In [149]:
sayi=1
while sayi<=30:
    print(sayi, end=' ')
    sayi+=2

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 

In [150]:
sayi= 0

while sayi <= 30:
    if sayi % 2 != 0:  # check if the number is odd
        print(sayi, end=' ')
    sayi += 1  # go to the next number


1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 

____________

# Create Lists with the range() Function

Use the range() function to create a list with all numbers from 1 to 10.

In [151]:
sayilar=list(range(1,11))
print(sayilar)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Use the range() function to create a list with all numbers from 0 to 19.

In [152]:
sayilar=list(range(0,20))
print(sayilar)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


Use the range function to create a list with all even numbers from 0 to 30 included.

In [153]:
ciftsayilar = list(range(0, 31))    # 0'dan 30'a kadar tüm sayılar
cift_sayilar = [n for n in ciftsayilar if n % 2 == 0]  # sadece çiftleri al
print(cift_sayilar)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


_______________________

# Use Conditional Statements and Loops Together

Create a For loop that will print all the variables from a given list multiplied by 2. Let the list contain all numbers from 1 to 10. Create it with the help of the range() function.

In [155]:
sayilar= list(range(1,11))
for n in sayilar:
    print(n*2, end=' ')

2 4 6 8 10 12 14 16 18 20 

Create a little program that runs a loop over all values from 1 to 30. Let it print all Odd numbers, and in the place of the even numbers, it should print "Even". Help yourself with the range() function to solve this exercise.

In [158]:
for d in range(1,31):
    if d % 2 != 0:
        print(d)
    else:
        print("tek")

1
tek
3
tek
5
tek
7
tek
9
tek
11
tek
13
tek
15
tek
17
tek
19
tek
21
tek
23
tek
25
tek
27
tek
29
tek


You have the following list of numbers. Iterate over this list, printing out each list value multiplied by 10. Find two solutions of this problem.

In [ ]:
n = [1,2,3,4,5,6]

In [159]:
n= [1,2,3,4,5,6]
for i in n:
    print(i*10)

10
20
30
40
50
60


In [160]:
n=[1,2,3,4,5,6]
result=[i*10 for i in n]
print(result)

[10, 20, 30, 40, 50, 60]


_________________

# All in - Conditional Statements, Functions, and Loops

You are provided with the 'nums' list. Complete the code in the cell that follows. Use a while loop to count the number of values lower than 20. You might prefer using the x[item] structure for indicating the value of an element from the list.

In [ ]:
nums = [1,12,24,31,51,70,100]

In [161]:
nums = [1, 12, 24, 31, 51, 70, 100]
count = 0
index = 0

while index < len(nums):
    if nums[index] < 20:
        count += 1
    index += 1

print(count)

2


____________

# Iterating over Dictionaries

In this exercise you will use the same dictionaries as the ones we used in the lesson - "prices" and "quantity". This time, don't just calculate all the money Jan spent. Calculate how much she spent on products with a price of 5 dollars or more.

In [ ]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

And how much did Jan spent on products that cost less than 5 dollars?

In [ ]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [162]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

for item in prices:
    if prices[item] >= 5:
        money_spent += prices[item] * quantity[item]

print(f"Jan spent ${money_spent} on products with a price of $5 or more.")

Jan spent $50 on products with a price of $5 or more.
